name: Build and Release ESAF Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Read VERSION file
      id: get_version
      run: |
        $version = Get-Content VERSION -Raw
        $version = $version.Trim()
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "Release version: $version"

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed ^
          --add-data "esaf_config_defaults.json;." ^
          --hidden-import=pandas ^
          --hidden-import=openpyxl ^
          --hidden-import=xlrd ^
          --hidden-import=plotly ^
          --hidden-import=pyautogui ^
          --hidden-import=pyperclip ^
          --hidden-import=pygetwindow ^
          --hidden-import=PIL ^
          --hidden-import=keyboard ^
          --hidden-import=colorama ^
          --hidden-import=cv2 ^
          autopilot.py

    - name: Verify .exe was built
      run: |
        if (Test-Path "dist\\autopilot.exe") {
          Write-Host "✅ .exe built successfully"
        } else {
          Write-Error "❌ .exe not found in dist folder"
          exit 1
        }

    - name: Rename executable
      run: |
        Move-Item "dist\\autopilot.exe" "dist\\esaf-automation-v$($env:VERSION).exe"

    - name: Upload artifact (for debugging)
      uses: actions/upload-artifact@v4
      with:
        name: esaf-automation-exe
        path: dist/esaf-automation-v${{ steps.get_version.outputs.VERSION }}.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        body: |
          Automated release of ESAF Automation Suite.
          
          Includes:
          - Full UI automation
          - Smart assignment engine
          - Executive dashboard
          
          **How to use**: Download the `.exe`, run it, and follow the menu.
        draft: true

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: release-asset
        path: dist/esaf-automation-v${{ steps.get_version.outputs.VERSION }}.exe
